version: "3.8"

services:
#  nginx:
#    image: nginx:latest
#    ports:
#      - "80:80"

  app:
    build:
      context: ./app
      target: development
    volumes:
      - ./app/src:/app/src
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
